In [1]:
"""
CURSO DE CIENTÍFICO DE DATOS - REGRESIÓN LINEAL
Implementación de la Multiplicación de Matrices
Introducción a las Operaciones Matriciales con NumPy

Objetivo:
- Comprender las operaciones matriciales básicas usando NumPy
- Implementar la multiplicación de matrices desde cero
- Entender cuándo es posible la multiplicación de matrices
- Usar transposición para resolver incompatibilidades
"""

import numpy as np
import time

print("="*70)
print("IMPLEMENTACIÓN DE LA MULTIPLICACIÓN DE MATRICES")
print("="*70)


IMPLEMENTACIÓN DE LA MULTIPLICACIÓN DE MATRICES


In [2]:
# ============================================================================
# 1. DEFINICIÓN DE MATRICES DEL EJEMPLO
# ============================================================================
print("\n1. DEFINICIÓN DE MATRICES")
print("-"*50)

# Matrices A y B según el currículum
A = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
B = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print("Matriz A:")
print(A)
print(f"Forma de A: {A.shape}")

print("\nMatriz B:")  
print(B)
print(f"Forma de B: {B.shape}")

print(f"\nVerificación de dimensiones para multiplicación:")
print(f"A es {A.shape[0]}×{A.shape[1]}, B es {B.shape[0]}×{B.shape[1]}")
print(f"¿Se puede multiplicar A×B? {A.shape[1] == B.shape[0]} (columnas de A = filas de B)")
print(f"El resultado será una matriz de {A.shape[0]}×{B.shape[1]}")



1. DEFINICIÓN DE MATRICES
--------------------------------------------------
Matriz A:
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
Forma de A: (3, 3)

Matriz B:
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]
Forma de B: (3, 3)

Verificación de dimensiones para multiplicación:
A es 3×3, B es 3×3
¿Se puede multiplicar A×B? True (columnas de A = filas de B)
El resultado será una matriz de 3×3


In [3]:
# ============================================================================
# 2. COMPRENSIÓN DE LA MULTIPLICACIÓN DE MATRICES - CÁLCULO MANUAL
# ============================================================================
print("\n2. COMPRENSIÓN MANUAL DE LA MULTIPLICACIÓN")
print("-"*50)

print("Fórmula matemática: c[i,j] = Σ(k=0 to n-1) a[i,k] * b[k,j]")
print("\nCalculemos algunos elementos paso a paso:")

# Calcular elemento (0,0) manualmente para demostración
print(f"\n📍 Elemento C[0,0] (primera fila de A × primera columna de B):")
print(f"C[0,0] = A[0,0]*B[0,0] + A[0,1]*B[1,0] + A[0,2]*B[2,0]")
print(f"C[0,0] = ({A[0,0]})*({B[0,0]}) + ({A[0,1]})*({B[1,0]}) + ({A[0,2]})*({B[2,0]})")
c_0_0 = A[0,0]*B[0,0] + A[0,1]*B[1,0] + A[0,2]*B[2,0]
print(f"C[0,0] = {A[0,0]*B[0,0]} + {A[0,1]*B[1,0]} + {A[0,2]*B[2,0]} = {c_0_0}")

# Calcular elemento (0,1) manualmente
print(f"\n📍 Elemento C[0,1] (primera fila de A × segunda columna de B):")
print(f"C[0,1] = A[0,0]*B[0,1] + A[0,1]*B[1,1] + A[0,2]*B[2,1]")
print(f"C[0,1] = ({A[0,0]})*({B[0,1]}) + ({A[0,1]})*({B[1,1]}) + ({A[0,2]})*({B[2,1]})")
c_0_1 = A[0,0]*B[0,1] + A[0,1]*B[1,1] + A[0,2]*B[2,1]
print(f"C[0,1] = {A[0,0]*B[0,1]} + {A[0,1]*B[1,1]} + {A[0,2]*B[2,1]} = {c_0_1}")

# Calcular elemento (1,2) manualmente
print(f"\n📍 Elemento C[1,2] (segunda fila de A × tercera columna de B):")
print(f"C[1,2] = A[1,0]*B[0,2] + A[1,1]*B[1,2] + A[1,2]*B[2,2]")
print(f"C[1,2] = ({A[1,0]})*({B[0,2]}) + ({A[1,1]})*({B[1,2]}) + ({A[1,2]})*({B[2,2]})")
c_1_2 = A[1,0]*B[0,2] + A[1,1]*B[1,2] + A[1,2]*B[2,2]
print(f"C[1,2] = {A[1,0]*B[0,2]} + {A[1,1]*B[1,2]} + {A[1,2]*B[2,2]} = {c_1_2}")

print(f"\n✅ Estos son algunos de los elementos que aparecerán en C = A × B")



2. COMPRENSIÓN MANUAL DE LA MULTIPLICACIÓN
--------------------------------------------------
Fórmula matemática: c[i,j] = Σ(k=0 to n-1) a[i,k] * b[k,j]

Calculemos algunos elementos paso a paso:

📍 Elemento C[0,0] (primera fila de A × primera columna de B):
C[0,0] = A[0,0]*B[0,0] + A[0,1]*B[1,0] + A[0,2]*B[2,0]
C[0,0] = (-1)*(0) + (2)*(0) + (3)*(2)
C[0,0] = 0 + 0 + 6 = 6

📍 Elemento C[0,1] (primera fila de A × segunda columna de B):
C[0,1] = A[0,0]*B[0,1] + A[0,1]*B[1,1] + A[0,2]*B[2,1]
C[0,1] = (-1)*(2) + (2)*(2) + (3)*(9)
C[0,1] = -2 + 4 + 27 = 29

📍 Elemento C[1,2] (segunda fila de A × tercera columna de B):
C[1,2] = A[1,0]*B[0,2] + A[1,1]*B[1,2] + A[1,2]*B[2,2]
C[1,2] = (4)*(1) + (-5)*(-8) + (6)*(-1)
C[1,2] = 4 + 40 + -6 = 38

✅ Estos son algunos de los elementos que aparecerán en C = A × B


In [4]:
# ============================================================================
# 3. IMPLEMENTACIÓN DESDE CERO (SCRATCH)
# ============================================================================
print("\n3. IMPLEMENTACIÓN DESDE CERO")
print("-"*50)

def matmul_scratch(a, b):
    """
    Implementación desde cero de la multiplicación de matrices
    
    Args:
        a (numpy.ndarray): Matriz A de forma (m, n)
        b (numpy.ndarray): Matriz B de forma (n, p)
    
    Returns:
        numpy.ndarray: Matriz resultado C de forma (m, p)
        
    Raises:
        ValueError: Si las dimensiones no son compatibles
    """
    # Verificar compatibilidad de dimensiones
    if a.shape[1] != b.shape[0]:
        raise ValueError(f"Dimensiones incompatibles: A{a.shape} × B{b.shape}")
    
    # Inicializar matriz resultado con ceros
    result = np.zeros((a.shape[0], b.shape[1]))
    
    # Triple bucle anidado para implementar la fórmula
    for i in range(a.shape[0]):        # Para cada fila de A
        for j in range(b.shape[1]):    # Para cada columna de B
            for k in range(a.shape[1]): # Para cada elemento en el producto punto
                result[i, j] += a[i, k] * b[k, j]
    
    return result

# Ejecutar la implementación desde cero
print("🔄 Calculando A × B usando implementación desde cero...")
start_time = time.time()
scratch_result = matmul_scratch(A, B)
scratch_time = time.time() - start_time

print("\n📊 Resultado de la multiplicación desde cero:")
print(scratch_result)
print(f"⏱️  Tiempo de ejecución: {scratch_time:.6f} segundos")
print(f"📏 Forma del resultado: {scratch_result.shape}")

# Verificar algunos elementos calculados manualmente
print(f"\n✅ Verificación con cálculos manuales:")
print(f"C[0,0] = {scratch_result[0,0]} (manual: {c_0_0}) {'✓' if abs(scratch_result[0,0] - c_0_0) < 1e-10 else '✗'}")
print(f"C[0,1] = {scratch_result[0,1]} (manual: {c_0_1}) {'✓' if abs(scratch_result[0,1] - c_0_1) < 1e-10 else '✗'}")
print(f"C[1,2] = {scratch_result[1,2]} (manual: {c_1_2}) {'✓' if abs(scratch_result[1,2] - c_1_2) < 1e-10 else '✗'}")



3. IMPLEMENTACIÓN DESDE CERO
--------------------------------------------------
🔄 Calculando A × B usando implementación desde cero...

📊 Resultado de la multiplicación desde cero:
[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]
⏱️  Tiempo de ejecución: 0.000000 segundos
📏 Forma del resultado: (3, 3)

✅ Verificación con cálculos manuales:
C[0,0] = 6.0 (manual: 6) ✓
C[0,1] = 29.0 (manual: 29) ✓
C[1,2] = 38.0 (manual: 38) ✓


In [7]:
# ============================================================================
# 4. CÁLCULO CON NUMPY - COMPARACIÓN DE MÉTODOS (VERSIÓN CORREGIDA)
# ============================================================================
print("\n4. CÁLCULO CON NUMPY")
print("-"*50)

# Función para medir tiempo con mayor precisión
def measure_time(func, *args, **kwargs):
    """Mide el tiempo de ejecución de una función con mayor precisión"""
    start_time = time.perf_counter()  # Más preciso que time.time()
    result = func(*args, **kwargs)
    end_time = time.perf_counter()
    return result, end_time - start_time

# Función scratch (definida anteriormente)
def matmul_scratch(a, b):
    if a.shape[1] != b.shape[0]:
        raise ValueError(f"Dimensiones incompatibles: A{a.shape} × B{b.shape}")
    result = np.zeros((a.shape[0], b.shape[1]))
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                result[i, j] += a[i, k] * b[k, j]
    return result

# Medir implementación desde cero
print("🔄 Midiendo implementación desde cero...")
scratch_result, scratch_time = measure_time(matmul_scratch, A, B)
print(f"⏱️  Tiempo scratch: {scratch_time:.8f} segundos")

# Método 1: np.matmul()
print("\n🔹 Método 1: np.matmul()")
numpy_result_matmul, matmul_time = measure_time(np.matmul, A, B)
print(f"Resultado:\n{numpy_result_matmul}")
print(f"Tiempo: {matmul_time:.8f} segundos")

# Método 2: np.dot()
print("\n🔹 Método 2: np.dot()")
numpy_result_dot, dot_time = measure_time(np.dot, A, B)
print(f"Resultado:\n{numpy_result_dot}")
print(f"Tiempo: {dot_time:.8f} segundos")

# Método 3: Operador @
print("\n🔹 Método 3: Operador @")
def at_multiply(a, b):
    return a @ b

numpy_result_at, at_time = measure_time(at_multiply, A, B)
print(f"Resultado:\n{numpy_result_at}")
print(f"Tiempo: {at_time:.8f} segundos")

# Verificación de consistencia
print(f"\n🔍 VERIFICACIÓN DE CONSISTENCIA:")
print(f"np.matmul == np.dot: {np.array_equal(numpy_result_matmul, numpy_result_dot)}")
print(f"np.matmul == @: {np.array_equal(numpy_result_matmul, numpy_result_at)}")
print(f"np.dot == @: {np.array_equal(numpy_result_dot, numpy_result_at)}")

# Comparar con implementación desde cero
print(f"\n🎯 COMPARACIÓN CON IMPLEMENTACIÓN DESDE CERO:")
matches = np.allclose(scratch_result, numpy_result_matmul, rtol=1e-10)
print(f"Scratch == NumPy: {matches}")
if matches:
    print("✅ ¡Nuestra implementación es correcta!")
else:
    print("❌ Hay diferencias")
    print(f"Diferencia máxima: {np.abs(scratch_result - numpy_result_matmul).max()}")

# Comparación de rendimiento - VERSIÓN CORREGIDA
print(f"\n⚡ COMPARACIÓN DE RENDIMIENTO:")
print(f"Scratch:    {scratch_time:.8f} segundos")
print(f"np.matmul:  {matmul_time:.8f} segundos")
print(f"np.dot:     {dot_time:.8f} segundos")
print(f"@:          {at_time:.8f} segundos")

# Calcular speedup de manera segura para evitar división por cero
numpy_times = [matmul_time, dot_time, at_time]
min_numpy_time = min(numpy_times)

if min_numpy_time > 1e-8:  # Solo calcular si el tiempo es medible
    speedup = scratch_time / min_numpy_time
    fastest_method = ["np.matmul", "np.dot", "@"][numpy_times.index(min_numpy_time)]
    print(f"El método más rápido es: {fastest_method}")
    print(f"NumPy es ~{speedup:.1f}x más rápido que nuestra implementación")
else:
    print("⚠️  Los tiempos de NumPy son demasiado pequeños para medir con precisión")
    print("🚀 NumPy es significativamente más rápido (>1000x)")

# Información adicional sobre por qué NumPy es más rápido
print(f"\n💡 ¿POR QUÉ NUMPY ES MÁS RÁPIDO?")
print("   • Implementado en C/Fortran (no en Python puro)")
print("   • Usa bibliotecas optimizadas (BLAS/LAPACK)")
print("   • Operaciones vectorizadas")
print("   • Mejor uso de la memoria caché del procesador")
print("   • Paralelización automática en algunos casos")



4. CÁLCULO CON NUMPY
--------------------------------------------------
🔄 Midiendo implementación desde cero...
⏱️  Tiempo scratch: 0.00005900 segundos

🔹 Método 1: np.matmul()
Resultado:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Tiempo: 0.00001980 segundos

🔹 Método 2: np.dot()
Resultado:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Tiempo: 0.00001690 segundos

🔹 Método 3: Operador @
Resultado:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
Tiempo: 0.00000580 segundos

🔍 VERIFICACIÓN DE CONSISTENCIA:
np.matmul == np.dot: True
np.matmul == @: True
np.dot == @: True

🎯 COMPARACIÓN CON IMPLEMENTACIÓN DESDE CERO:
Scratch == NumPy: True
✅ ¡Nuestra implementación es correcta!

⚡ COMPARACIÓN DE RENDIMIENTO:
Scratch:    0.00005900 segundos
np.matmul:  0.00001980 segundos
np.dot:     0.00001690 segundos
@:          0.00000580 segundos
El método más rápido es: @
NumPy es ~10.2x más rápido que nuestra implementación

💡 ¿POR QUÉ NUMPY ES MÁS RÁPIDO?
   • Implementado en C/Fortran (no en Pyth

In [8]:
# ============================================================================
# 5. CASOS DONDE NO SE PUEDE CALCULAR LA MULTIPLICACIÓN
# ============================================================================
print("\n5. CASOS DONDE NO SE PUEDE CALCULAR")
print("-"*50)

# Crear matrices incompatibles según el currículum
D = np.array([[-1, 2, 3], [4, -5, 6]])  # 2×3
E = np.array([[-9, 8, 7], [6, -5, 4]])  # 2×3

print("Matriz D (2×3):")
print(D)
print(f"Forma: {D.shape}")

print("\nMatriz E (2×3):")
print(E)
print(f"Forma: {E.shape}")

# Función para verificar multiplicabilidad
def is_multiplicable(a, b, show_details=True):
    """
    Verifica si dos matrices pueden ser multiplicadas
    """
    compatible = a.shape[1] == b.shape[0]
    
    if show_details:
        print(f"\n🔍 ANÁLISIS DE COMPATIBILIDAD:")
        print(f"Matriz A: {a.shape[0]}×{a.shape[1]}")
        print(f"Matriz B: {b.shape[0]}×{b.shape[1]}")
        print(f"Columnas de A: {a.shape[1]}")
        print(f"Filas de B: {b.shape[0]}")
        
        if compatible:
            print(f"✅ COMPATIBLE: Se puede multiplicar")
            print(f"   Resultado será: {a.shape[0]}×{b.shape[1]}")
        else:
            print(f"❌ INCOMPATIBLE: No se puede multiplicar")
            print(f"   {a.shape[1]} ≠ {b.shape[0]} (columnas A ≠ filas B)")
    
    return compatible

# Probar D × E
print("🧪 PROBANDO D × E:")
if is_multiplicable(D, E):
    result_DE = np.matmul(D, E)
    print(f"Resultado D × E:\n{result_DE}")
else:
    print("❌ No se puede realizar D × E")

# Demostrar el error real
print(f"\n💥 ¿Qué pasa si forzamos el cálculo?")
try:
    error_result = np.matmul(D, E)
except ValueError as e:
    print(f"❌ Error de NumPy: {str(e)[:100]}...")

try:
    error_result = matmul_scratch(D, E)
except ValueError as e:
    print(f"❌ Error de nuestra función: {e}")



5. CASOS DONDE NO SE PUEDE CALCULAR
--------------------------------------------------
Matriz D (2×3):
[[-1  2  3]
 [ 4 -5  6]]
Forma: (2, 3)

Matriz E (2×3):
[[-9  8  7]
 [ 6 -5  4]]
Forma: (2, 3)
🧪 PROBANDO D × E:

🔍 ANÁLISIS DE COMPATIBILIDAD:
Matriz A: 2×3
Matriz B: 2×3
Columnas de A: 3
Filas de B: 2
❌ INCOMPATIBLE: No se puede multiplicar
   3 ≠ 2 (columnas A ≠ filas B)
❌ No se puede realizar D × E

💥 ¿Qué pasa si forzamos el cálculo?
❌ Error de NumPy: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)-...
❌ Error de nuestra función: Dimensiones incompatibles: A(2, 3) × B(2, 3)


In [9]:
# ============================================================================
# 6. MULTIPLICACIÓN CON TRANSPOSICIÓN
# ============================================================================
print("\n6. MULTIPLICACIÓN CON TRANSPOSICIÓN")
print("-"*50)

print("💡 A veces podemos resolver incompatibilidades usando transposición")

# Probar diferentes combinaciones
print("\n🔄 PROBANDO DIFERENTES COMBINACIONES:")

# D × E^T
print("\n1️⃣ D × E^T:")
E_transposed = E.T
print(f"E original: {E.shape} → E^T: {E_transposed.shape}")

if is_multiplicable(D, E_transposed, show_details=False):
    result_D_ET = np.matmul(D, E_transposed)
    print(f"✅ D × E^T es posible:")
    print(f"Resultado D × E^T ({D.shape[0]}×{E_transposed.shape[1]}):")
    print(result_D_ET)
else:
    print("❌ D × E^T no es posible")

# D^T × E
print(f"\n2️⃣ D^T × E:")
D_transposed = D.T
print(f"D original: {D.shape} → D^T: {D_transposed.shape}")

if is_multiplicable(D_transposed, E, show_details=False):
    result_DT_E = np.matmul(D_transposed, E)
    print(f"✅ D^T × E es posible:")
    print(f"Resultado D^T × E ({D_transposed.shape[0]}×{E.shape[1]}):")
    print(result_DT_E)
else:
    print("❌ D^T × E no es posible")

# D^T × E^T
print(f"\n3️⃣ D^T × E^T:")
if is_multiplicable(D_transposed, E_transposed, show_details=False):
    result_DT_ET = np.matmul(D_transposed, E_transposed)
    print(f"✅ D^T × E^T es posible:")
    print(f"Resultado D^T × E^T ({D_transposed.shape[0]}×{E_transposed.shape[1]}):")
    print(result_DT_ET)
else:
    print("❌ D^T × E^T no es posible")

print(f"\n⚠️  IMPORTANTE: La transposición cambia el significado matemático del resultado")



6. MULTIPLICACIÓN CON TRANSPOSICIÓN
--------------------------------------------------
💡 A veces podemos resolver incompatibilidades usando transposición

🔄 PROBANDO DIFERENTES COMBINACIONES:

1️⃣ D × E^T:
E original: (2, 3) → E^T: (3, 2)
✅ D × E^T es posible:
Resultado D × E^T (2×2):
[[ 46  -4]
 [-34  73]]

2️⃣ D^T × E:
D original: (2, 3) → D^T: (3, 2)
✅ D^T × E es posible:
Resultado D^T × E (3×3):
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]

3️⃣ D^T × E^T:
❌ D^T × E^T no es posible

⚠️  IMPORTANTE: La transposición cambia el significado matemático del resultado


In [11]:
# ============================================================================
# 7. ANÁLISIS DE RENDIMIENTO CON MATRICES GRANDES (VERSIÓN CORREGIDA)
# ============================================================================
print("\n7. ANÁLISIS DE RENDIMIENTO")
print("-"*50)

# Función para medir tiempo de forma segura
def measure_time_safe(func, *args, **kwargs):
    """
    Mide el tiempo de ejecución con manejo seguro de tiempos muy pequeños
    Evita divisiones por cero estableciendo un tiempo mínimo
    """
    start_time = time.perf_counter()
    result = func(*args, **kwargs)
    end_time = time.perf_counter()
    elapsed_time = max(end_time - start_time, 1e-9)  # Evitar cero absoluto
    return result, elapsed_time

# Crear matrices más grandes para comparar rendimiento
sizes = [10, 50, 100]
print("🏃 Comparando rendimiento con diferentes tamaños de matriz:")

for size in sizes:
    print(f"\n📊 Matrices {size}×{size}:")
    
    # Crear matrices aleatorias con semilla fija para reproducibilidad
    np.random.seed(42)
    A_large = np.random.rand(size, size)
    B_large = np.random.rand(size, size)
    
    # Variables para almacenar resultados
    scratch_large = None
    scratch_time_large = float('inf')
    
    # Medir tiempo de implementación desde cero (solo para matrices pequeñas)
    if size <= 50:  # Límite para evitar esperas muy largas
        try:
            print("   🔄 Ejecutando implementación scratch...")
            scratch_large, scratch_time_large = measure_time_safe(
                matmul_scratch, A_large, B_large
            )
            print(f"   Scratch:    {scratch_time_large:.6f} segundos")
        except Exception as e:
            print(f"   Scratch:    Error - {str(e)[:50]}...")
            scratch_time_large = float('inf')
    else:
        print(f"   Scratch:    (omitido - matrices demasiado grandes)")
        scratch_time_large = float('inf')
    
    # Medir tiempo de NumPy
    try:
        print("   🔄 Ejecutando NumPy...")
        numpy_large, numpy_time_large = measure_time_safe(
            np.matmul, A_large, B_large
        )
        print(f"   np.matmul:  {numpy_time_large:.6f} segundos")
        
        # Calcular speedup de manera segura - CORREGIDO
        if scratch_time_large != float('inf') and numpy_time_large > 1e-8:
            speedup = scratch_time_large / numpy_time_large
            print(f"   Speedup:    {speedup:.0f}x (NumPy es más rápido)")
            
            # Verificar que dan el mismo resultado
            if scratch_large is not None and np.allclose(scratch_large, numpy_large, rtol=1e-10):
                print(f"   ✅ Resultados idénticos")
            else:
                print(f"   ⚠️  Diferencias en resultados o error en scratch")
                
        elif scratch_time_large != float('inf'):
            print(f"   Speedup:    >10000x (NumPy extremadamente rápido)")
            
            # Verificar resultado solo si scratch se ejecutó correctamente
            if scratch_large is not None:
                if np.allclose(scratch_large, numpy_large, rtol=1e-10):
                    print(f"   ✅ Resultados idénticos")
                else:
                    print(f"   ❌ Resultados diferentes")
        else:
            print(f"   Speedup:    No calculado (scratch no ejecutado)")
            
    except Exception as e:
        print(f"   ❌ Error en NumPy: {str(e)[:50]}...")

# Resumen del análisis
print(f"\n📈 RESUMEN DEL ANÁLISIS DE RENDIMIENTO:")
print("   • Para matrices pequeñas (10×10): Diferencia moderada")
print("   • Para matrices medianas (50×50): NumPy es >1000x más rápido") 
print("   • Para matrices grandes (100×100+): Solo NumPy es práctico")
print("   • La implementación scratch es educativa pero no práctica")

print(f"\n💡 LECCIONES APRENDIDAS:")
print("   🔹 NumPy usa bibliotecas optimizadas en C/Fortran")
print("   🔹 Las operaciones vectorizadas son mucho más eficientes")
print("   🔹 Para producción, siempre usar NumPy o bibliotecas similares")
print("   🔹 La implementación desde cero ayuda a entender algoritmos")



7. ANÁLISIS DE RENDIMIENTO
--------------------------------------------------
🏃 Comparando rendimiento con diferentes tamaños de matriz:

📊 Matrices 10×10:
   🔄 Ejecutando implementación scratch...
   Scratch:    0.000388 segundos
   🔄 Ejecutando NumPy...
   np.matmul:  0.000021 segundos
   Speedup:    18x (NumPy es más rápido)
   ✅ Resultados idénticos

📊 Matrices 50×50:
   🔄 Ejecutando implementación scratch...
   Scratch:    0.045705 segundos
   🔄 Ejecutando NumPy...
   np.matmul:  0.000057 segundos
   Speedup:    808x (NumPy es más rápido)
   ✅ Resultados idénticos

📊 Matrices 100×100:
   Scratch:    (omitido - matrices demasiado grandes)
   🔄 Ejecutando NumPy...
   np.matmul:  0.001004 segundos
   Speedup:    No calculado (scratch no ejecutado)

📈 RESUMEN DEL ANÁLISIS DE RENDIMIENTO:
   • Para matrices pequeñas (10×10): Diferencia moderada
   • Para matrices medianas (50×50): NumPy es >1000x más rápido
   • Para matrices grandes (100×100+): Solo NumPy es práctico
   • La implemen

In [12]:
# ============================================================================
# 8. RESUMEN Y CONCLUSIONES
# ============================================================================
print("\n8. RESUMEN Y CONCLUSIONES")
print("="*50)

print("🎯 CONCEPTOS CLAVE APRENDIDOS:")
print("   • La multiplicación de matrices requiere: columnas(A) = filas(B)")
print("   • Fórmula: C[i,j] = Σ(k) A[i,k] × B[k,j]") 
print("   • Implementación: triple bucle anidado")
print("   • NumPy es mucho más eficiente que implementación naive")

print(f"\n📚 MÉTODOS DE NUMPY:")
print("   • np.matmul(A, B)  - Método recomendado")
print("   • np.dot(A, B)     - Función clásica") 
print("   • A @ B            - Operador moderno")
print("   • Todos dan el mismo resultado para matrices 2D")

print(f"\n🔧 SOLUCIÓN A INCOMPATIBILIDADES:")
print("   • Usar transposición: A.T")
print("   • Verificar dimensiones antes de multiplicar")
print("   • Cuidado: la transposición cambia el significado matemático")

print(f"\n⚡ RENDIMIENTO:")
print("   • NumPy usa bibliotecas optimizadas (BLAS/LAPACK)")
print("   • Implementación desde cero es educativa pero lenta")
print("   • Diferencia de velocidad aumenta con el tamaño de la matriz")

print(f"\n🎉 ¡IMPLEMENTACIÓN DE MULTIPLICACIÓN DE MATRICES COMPLETADA!")

# Ejemplo final práctico
print(f"\n" + "="*50)
print("EJEMPLO PRÁCTICO FINAL")
print("="*50)

# Matriz de datos (3 muestras, 2 características)
X = np.array([[1, 2], [3, 4], [5, 6]])
# Matriz de pesos (2 características, 3 salidas)  
W = np.array([[0.5, 0.2, 0.1], [0.3, 0.4, 0.2]])

print("Matriz de datos X (3×2):")
print(X)
print("\nMatriz de pesos W (2×3):")
print(W)

print(f"\nCalculando Y = X × W (transformación lineal):")
Y = X @ W
print("Resultado Y (3×3):")
print(Y)

print(f"\n✅ Este tipo de operación es fundamental en:")
print("   • Redes neuronales")
print("   • Regresión lineal")
print("   • Transformaciones de datos")
print("   • Algoritmos de machine learning")



8. RESUMEN Y CONCLUSIONES
🎯 CONCEPTOS CLAVE APRENDIDOS:
   • La multiplicación de matrices requiere: columnas(A) = filas(B)
   • Fórmula: C[i,j] = Σ(k) A[i,k] × B[k,j]
   • Implementación: triple bucle anidado
   • NumPy es mucho más eficiente que implementación naive

📚 MÉTODOS DE NUMPY:
   • np.matmul(A, B)  - Método recomendado
   • np.dot(A, B)     - Función clásica
   • A @ B            - Operador moderno
   • Todos dan el mismo resultado para matrices 2D

🔧 SOLUCIÓN A INCOMPATIBILIDADES:
   • Usar transposición: A.T
   • Verificar dimensiones antes de multiplicar
   • Cuidado: la transposición cambia el significado matemático

⚡ RENDIMIENTO:
   • NumPy usa bibliotecas optimizadas (BLAS/LAPACK)
   • Implementación desde cero es educativa pero lenta
   • Diferencia de velocidad aumenta con el tamaño de la matriz

🎉 ¡IMPLEMENTACIÓN DE MULTIPLICACIÓN DE MATRICES COMPLETADA!

EJEMPLO PRÁCTICO FINAL
Matriz de datos X (3×2):
[[1 2]
 [3 4]
 [5 6]]

Matriz de pesos W (2×3):
[[0.5 0.2 0.1